# Generated by Django 5.0 on 2023-12-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManytoManyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listener',
            name='songs',
            field=models.ManyToManyField(related_name='Song', related_query_name='song', to='ManytoManyApp.song'),
        ),
    ]
